#!/bin/sh /etc/rc.common
#=============================================================================
#  Copyright (c) YOUKU, 2014. All rights reserved.
# 
#  @author    yang <yangjingyu@youku.com>
# 
#  @brief	  
# 
#  Revision History:
#=============================================================================

START=99
STOP=00 

USE_PROCD=1

start_service() {

	/etc/youku/rc.main start 

#	start youku framework with respawn mode
	[ -f /tmp/youku/bin/youkucmc ] && {
		procd_open_instance
  		procd_set_param command /tmp/youku/bin/youkucmc
  		procd_set_param respawn # respawn automatically if something died, be careful if you have an alternative process supervisor
        procd_append_param respawn 60
        procd_append_param respawn 1
        procd_append_param respawn -1
#  		procd_set_param env     SOME_VARIABLE=funtimes  # pass environment variables to your process
#  		procd_set_param limits core="unlimited"  #If you need to set ulimit for your process
  		procd_close_instance

		/etc/youku/rc.main ylog "procd start youkucmc service..."
	}
	
}

stop_service() {
	/etc/youku/rc.main ylog "procd stop youku service..."
	/etc/youku/rc.main stop
}

# system monitor when config changed by uci interface.
service_triggers()
{
#	-rw-r--r--    1 root     root           687 Aug 14  2014 6relayd
#	-rw-r--r--    1 root     root            25 Aug 25  2014 account
#	-rw-r--r--    1 root     root           134 Aug 14  2014 dropbear
#	-rwxrwxrwx    1 root     root           312 Aug  8  2014 fstab
#	-rw-------    1 root     root           669 Jan  1 00:00 luci
#	-rwxrwxrwx    1 root     root           717 Aug  8  2014 ucitrack
#	-rw-r--r--    1 root     root          3388 Aug 14  2014 uhttpd

#       procd_add_reload_trigger "network" "wireless" "dhcp" "system"
#	procd_add_network_trigger "lan"|"etho0" # FIXME - this is still a work in process....

	procd_add_config_trigger "system" "/etc/youku/rc.main" "notify" "system" 
	procd_add_config_trigger "network" "/etc/youku/rc.main" "notify" "network" 
	procd_add_config_trigger "wireless" "/etc/youku/rc.main" "notify" "wireless" 
	procd_add_config_trigger "dhcp" "/etc/youku/rc.main" "notify" "dhcp"
	procd_add_config_trigger "firewall" "/etc/youku/rc.main" "notify" "firewall"
}

reload()
{
#     	service_reload as default
#	now used to notify ikuacc and(or) framework
	/etc/youku/rc.main ylog "procd relaod youku service [test only]..."
}


