#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner
[ -f /etc/youku/build-info ] && cat /etc/youku/build/banner
#[ -f /etc/localrev ] && cat /etc/localrev

#2014-08-28,yangjingyu, use YoukuHome 
export YoukuHome=/tmp/youku
export PATH=$YoukuHome:$YoukuHome/bin:/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
#export HOME=$YoukuHome
export PS1='[\u@\h]'

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

export PKG_HOME=${YoukuHome}/pkg
export PATH=${PATH}:${PKG_HOME}/bin:${PKG_HOME}/sbin:${PKG_HOME}/usr/bin:${PKG_HOME}/usr/sbin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PKG_HOME}/lib:${PKG_HOME}/usr/lib
