#!/bin/sh /etc/rc.common

START=92
USE_PROCD=1

start_instance(){
	config_get cmd "$1" command
	
	if [ -x "$cmd" ]; then
		procd_open_instance
		procd_set_param command "$cmd"
		procd_set_param respawn
		procd_close_instance
	fi
}

start_service() {
	config_load /etc/youku/ubus
	config_foreach start_instance ubus
}
